#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Generate a text-only KMI/ABI baseline manifest for the marble 6.18 build.
# This script never packages images and never reads or writes device artefacts.
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "usage: $0 <kernel-out-dir> <report-dir>" >&2
    exit 2
fi

OUT_DIR=$(realpath "$1")
REPORT_DIR=$(realpath -m "$2")
ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)

for required in \
    "$OUT_DIR/.config" \
    "$OUT_DIR/Module.symvers" \
    "$OUT_DIR/vmlinux" \
    "$OUT_DIR/arch/arm64/boot/Image" \
    "$OUT_DIR/include/generated/utsrelease.h" \
    "$OUT_DIR/build-metadata.txt"; do
    [[ -s "$required" ]] || { echo "missing required input: $required" >&2; exit 1; }
done

ABI_AUDIT_DIR="$ROOT_DIR/marble-port/reports/evolutionx17_rom_abi_audit"
for required in \
    "$ABI_AUDIT_DIR/module_summary.tsv" \
    "$ABI_AUDIT_DIR/module_gap_families.tsv" \
    "$ABI_AUDIT_DIR/first_stage_load_filename_gaps.txt" \
    "$ABI_AUDIT_DIR/vendor_load_filename_gaps.txt"; do
    [[ -s "$required" ]] || { echo "missing vendor audit input: $required" >&2; exit 1; }
done

rm -rf "$REPORT_DIR"
mkdir -p "$REPORT_DIR"

CONFIG="$OUT_DIR/.config"
SYMVERS="$OUT_DIR/Module.symvers"
VMLINUX="$OUT_DIR/vmlinux"
IMAGE="$OUT_DIR/arch/arm64/boot/Image"
KERNEL_RELEASE=$(sed -n 's/^#define UTS_RELEASE "\(.*\)"/\1/p' "$OUT_DIR/include/generated/utsrelease.h")
BUILD_COMMIT=$(sed -n 's/^source_commit=//p' "$OUT_DIR/build-metadata.txt")
ANALYSIS_COMMIT=$(git -C "$ROOT_DIR" rev-parse HEAD)
MODULE_COUNT=$(find "$OUT_DIR" -type f -name '*.ko' | wc -l)
SYMVERS_LINES=$(wc -l < "$SYMVERS")
SYMVERS_MODULES=$(awk 'NF >= 3 { print $3 }' "$SYMVERS" | sort -u | wc -l)
EXPORT_SYMBOL=$(awk 'NF >= 4 && $4 == "EXPORT_SYMBOL" { count++ } END { print count + 0 }' "$SYMVERS")
EXPORT_GPL=$(awk 'NF >= 4 && $4 == "EXPORT_SYMBOL_GPL" { count++ } END { print count + 0 }' "$SYMVERS")

(
    cd "$OUT_DIR"
    sha256sum .config Module.symvers vmlinux arch/arm64/boot/Image
) > "$REPORT_DIR/artifact_sha256.txt"
awk 'NF >= 4 { print $2 "\t" $3 "\t" $4 "\t" (NF >= 5 ? $5 : "-") }' "$SYMVERS" \
    | LC_ALL=C sort \
    | sha256sum \
    | awk '{ print $1 "  normalized_module_symvers.tsv" }' \
    > "$REPORT_DIR/normalized_module_symvers.sha256"

{
    echo "# marble 6.18 KMI/ABI Baseline Manifest"
    echo
    echo "**Generated by:** \`tools/generate_marble_kmi_baseline.sh\`"
    echo
    echo "## Scope"
    echo
    echo "This is a reproducible, text-only baseline for the current marble 6.18 diagnostic build. It identifies the configuration, module-symbol table, and vendor-gap audit inputs that future source-built vendor modules must be compared against. It is not an Android GKI certification, an approved product KMI, or proof that any 5.10 vendor binary can load on 6.18."
    echo
    echo "## Build identity"
    echo
    echo "| Field | Value |"
    echo "|---|---|"
    echo "| Analysis source commit | \`$ANALYSIS_COMMIT\` |"
    echo "| Build source commit | \`$BUILD_COMMIT\` |"
    echo "| Kernel release | \`$KERNEL_RELEASE\` |"
    echo "| Output directory | \`out/marble-aosp-release-6.18.32-r1\` |"
    echo "| Module count | \`$MODULE_COUNT\` |"
    echo "| Module.symvers rows | \`$SYMVERS_LINES\` |"
    echo "| Distinct exporting objects | \`$SYMVERS_MODULES\` |"
    echo "| EXPORT_SYMBOL entries | \`$EXPORT_SYMBOL\` |"
    echo "| EXPORT_SYMBOL_GPL entries | \`$EXPORT_GPL\` |"
    echo
    echo "## ABI-relevant configuration"
    echo
    echo "| Configuration | Value |"
    echo "|---|---|"
    for name in CONFIG_MODULES CONFIG_MODVERSIONS CONFIG_MODULE_SIG CONFIG_DEBUG_INFO_BTF CONFIG_DEBUG_INFO_BTF_MODULES; do
        value=$(grep -E "^${name}=" "$CONFIG" | cut -d= -f2- || true)
        echo "| \`$name\` | \`${value:-not-set}\` |"
    done
    echo
    echo "The hashes below bind this report to exact local build artefacts. The raw \`Module.symvers\`, \`.config\`, \`vmlinux\`, and Image remain build outputs and are not committed to Git."
    echo
    echo '```text'
    cat "$REPORT_DIR/artifact_sha256.txt"
    cat "$REPORT_DIR/normalized_module_symvers.sha256"
    echo '```'
    echo
    echo "## Vendor-gap evidence"
    echo
    echo "The following tables were generated earlier from the single Evolution X 17 reference artefact set. They are included as a planning baseline only; they do not introduce ROM binaries into this repository."
    echo
    echo '```tsv'
    cat "$ABI_AUDIT_DIR/module_summary.tsv"
    cat "$ABI_AUDIT_DIR/module_gap_families.tsv"
    echo '```'
    echo
    echo "The audited first-stage module-name gap contains \`$(wc -l < "$ABI_AUDIT_DIR/first_stage_load_filename_gaps.txt")\` entries. The vendor-load module-name gap contains \`$(wc -l < "$ABI_AUDIT_DIR/vendor_load_filename_gaps.txt")\` entries. These are name-level lower bounds; symbol, firmware, Device Tree, ramdisk, and userspace dependencies are separate work items."
    echo
    echo "## Acceptance rule for future vendor modules"
    echo
    echo "Every candidate 6.18 vendor module must be source-built against this frozen baseline or a deliberately revised successor. It must have reviewed configuration, matching vermagic/modversion semantics, approved exported-symbol dependencies, a load-order and firmware plan, and a driver contract. A 5.10 binary, or a module matched only by filename, is rejected."
    echo
    echo "## References"
    echo
    echo "- [Evolution X 17 ABI and DTBO compatibility analysis](../../EVOLUTIONX17_COMPATIBILITY_ANALYSIS.md)"
    echo "- [Vendor/KMI and boot-image engineering plan](../../VENDOR_KMI_BOOT_IMAGE_ENGINEERING_PLAN.md)"
    echo "- [AOSP GKI/KMI reference notes](../../ANDROID_GKI_KMI_BOOT_REFERENCE_2026-08-22.md)"
} > "$REPORT_DIR/KMI_BASELINE_MANIFEST.md"

printf 'report=%s\n' "$REPORT_DIR/KMI_BASELINE_MANIFEST.md"
printf 'hashes=%s\n' "$REPORT_DIR/artifact_sha256.txt"
